#!/bin/sh

CONFIG_FILE=$HOME/.git2obsrc
LOG_FILE=/tmp/git2obs.$$

usage ()
{
	echo "Usage: git2obs directory version_prefix"
	exit 1
}

###
# we want pretty messages!

# COLS & COL
if [ "$COLS" ] && [ "$COLS" -gt 6 ]; then
	COL=`expr $COLS - 7`
else
	COLS=80
	COL=73
fi


if [ "$COLS" ] && [ "$COLS" -gt 6 ]; then
	COL=`expr $COLS - 7`
else
	COLS=80
	COL=73
fi

log_message ()
{
	echo -n " * $1"
}

log_message_end ()
{
	if [ -z "$1" ]; then
		return 1
	fi

	printf "\r"
	tput hpa $COL
	if [ "$1" -eq 0 ]; then
		printf '[ '
		tput setaf 2 # green
		printf OK
		tput op # normal
		echo ' ]'
	else
		printf '['
		tput setaf 1 # red
		printf fail
		tput op # normal
		echo ']'
	fi

	return $1
}

###
# okko message command
okko ()
{
	local message=$1
	local command=$2
	local result

	log_message "$message"
	echo "\$ $command" >> $LOG_FILE
	$command 2>&1 >> $LOG_FILE
        result=$?
	log_message_end $result
	if [ $result != 0 ]; then
		echo "Ooops... an error occured, see $LOG_FILE"
	fi
}

[ -f "$CONFIG_FILE" ] && source $CONFIG_FILE

# options
[ -z "$1" -o -z "$2" ] && usage
PKG_NAME=`basename "$1`
PKG_PATH=`echo "$1" | sed -e 's,/$,,`
VERSION_PREFIX=$2

# default values
[ -z "$G2O_SANDBOX_CHECKOUT" ] && G2O_SANDBOX_CHECKOUT=$HOME/moblin/UX
[ -z "$G2O_COMMIT_AUTHOR" ] && {
	G2O_COMMIT_AUTHOR="Damien Lespiau <damien.lespiau@intel.com>"
}

# input validation
[ -d "$PKG_PATH" ] || {
	echo "$PKG_PATH is not a directory."
	exit 1
}
[ -d "$G2O_SANDBOX_CHECKOUT/$PKG_NAME" ] || {
	echo "$G2O_SANDBOX_CHECKOUT/$PKG_NAME is not a directory."
	exit 1
}
[ -f "$G2O_SANDBOX_CHECKOUT/$PKG_NAME/$PKG_NAME.ini" ] || {
	echo "Could not find $G2O_SANDBOX_CHECKOUT/$PKG_NAME.ini"
	exit 1
}
[ -f "$G2O_SANDBOX_CHECKOUT/$PKG_NAME/$PKG_NAME.changes" ] || {
	echo "Could not find $PKG_NAME.changes"
	exit 1
}

DATE=`date +%Y%m%d`
VP=$VERSION_PREFIX

# be sure nothing is in the way
[ -d "/tmp/$PKG_NAME-$VP$DATE" ] && {
	echo "/tmp/$PKG_NAME-$VP$DATE is in the way, please remove it."
	exit 1
}
[ -d "/tmp/$PKG_NAME-$VP$DATE.tar.bz2" ] && {
	echo "/tmp/$PKG_NAME-$VP$DATE.tar.bz2 is in the way, please remove it."
	exit 1
}

# we just copy the whole directory, run git clean -xdf in it, remove .git
# and create a tarbal
cp -r $PKG_PATH /tmp/$PKG_NAME-$VP$DATE
cd /tmp/$PKG_NAME-$VP$DATE
COMMIT_HASH=`git show-ref -s HEAD | head -n 1`
git clean -xdf
rm -rf .git
cd -
tar -C /tmp -jcf $PKG_NAME-$VP$DATE.tar.bz2 $PKG_NAME-$VP$DATE
mv $PKG_NAME-$VP$DATE.tar.bz2 $G2O_SANDBOX_CHECKOUT/$PKG_NAME
[ -d /tmp/$PKG_NAME-$VP$DATE ] && rm -rf /tmp/$PKG_NAME-$VP$DATE

# update spec-builder metadata
COMMIT_DATE=`date +'%a %b %d %Y'`
cd $G2O_SANDBOX_CHECKOUT/$PKG_NAME
# add update info in .changes file
mv $PKG_NAME.changes $PKG_NAME.changes.orig
echo "* $COMMIT_DATE $G2O_COMMIT_AUTHOR $VP$DATE" > $PKG_NAME.changes
echo "- Update to commit $COMMIT_HASH" >> $PKG_NAME.changes
echo "" >> $PKG_NAME.changes
cat $PKG_NAME.changes.orig >> $PKG_NAME.changes
rm $PKG_NAME.changes.orig
# update the version in the ini file
sed -i -e "s,Version.*,Version = $VP$DATE," $PKG_NAME.ini
# run spec-builder to update the spec file
spec-builder $PKG_NAME.ini > $PKG_NAME.spec

